language: cpp

matrix:
  include:
    # GCC-9 
    - os: linux
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - gcc-9
          - lcov
    env:
      - MATRIX_EVAL="CC=gcc-9 CXX=g++-9"

    # Clang
    - os: linux
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - clang-9
          - lcov
    env:
      - MATRIX_EVAL="CC=clang-9 CXX=clang++-9"
    
before_install:
  - eval "${MATRIX_EVAL}"

script:
  - cmake --version
  - cmake CMakeLists.txt
  - cmake  --build . --target
  - ctest

after_success:
  - cd ${TRAVIS_BUILD_DIR}
  - lcov --directory . --capture --output-file coverage.info coverage info
  - lcov --remove coverage.info '/usr/*' --output-file coverage.info 
  - lcov --list coverage.info
  # Uploading report to CodeCov
  - bash <(curl -s https://codecov.io/bash) || echo "Codecov did not collect coverage reports"
