language: cpp

jobs:
  include:
    # GCC
    - os: linux
      dist: bionic
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-9
            - lcov
            - gcov-9
            - cmake
      env:
        - MATRIX_EVAL="CC=gcc-9 && CXX=g++-9"
      script:
        - gcc -v 
        - g++ -v
        - cmake --version
        - lcov -version
        - gcov -version
        - gcov-9 -version
        - cmake -DZBINARYREADER_CODE_COVERAGE=ON CMakeLists.txt
        - cmake  --build . --target
        - ctest -VV

    # # CLANG
    # - os: linux
    #   dist: bionic
    #   addons:
    #     apt:
    #       sources:
    #         - ubuntu-toolchain-r-test
    #       packages:
    #         - clang-9
    #         - cmake
    #   env:
    #     - MATRIX_EVAL="CC=clang-9 && CXX=clang++-9"
    #   script:
    #     - cmake --version
    #     - cmake CMakeLists.txt
    #     - cmake  --build . --target
    #     - ctest

    
before_install:
  - eval "${MATRIX_EVAL}"

  - wget http://downloads.sourceforge.net/ltp/lcov-1.14.tar.gz
  - tar -xvf lcov-1.14.tar.gz
  - cd lcov-1.14 && sudo make install
  - cd ..

after_success:
  - cd ${TRAVIS_BUILD_DIR}
  - lcov --directory . --capture --output-file coverage.info -gcov-tool /usr/bin/gcov-9
  - lcov --remove coverage.info '/usr/*' --output-file coverage.info 
  - lcov --list coverage.info
  - bash <(curl -s https://codecov.io/bash) || echo "Codecov did not collect coverage reports"

